server: 
  port: 80   # AJP 포트 설정
  logging:
  level:
    jdbc.resultset: ERROR
#tomcat:
#  protocol: AJP/1.3
#  secretRequired: false
#  ajp:
#    enabled: true
#    port: 8089   # 톰캣 AJP 포트 설정
#    secretRequired: false
file:
  uploadDir: D:\gunyang\upload 
spring:
  mailType: office365
#  Java MailSender
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    port: 587
    username: js.nam@gunyangitt.co.kr
    password: kkkk
    properties:
      mail:
        debuger: true
        smtp:
          port: 587
          transport:
            protocol: smtps
          auth: true
          timeout: 15000
          connectiontimeout: 15000
          starttls:            enable: true
            required: true
          ssl:
            enable: false
          socketFactory:
            fallback: true
#  mail:
#    default-encoding: UTF-8
#    host: smtp.gmail.com
#    port: 587
#    username: jangsub.nam
#    password: kkjj
#    properties:
#      mail:
#        debuger: true
#        smtp:
#          auth: true
#          timeout: 5000
#          starttls:
#            enable: true

          