server: 
  port: 80   # AJP 포트 설정
logging:
  level:
    root: INFO
    jdbc.resultset: ERROR
#tomcat:
#  protocol: AJP/1.3
#  secretRequired: false
#  ajp:
#    enabled: true
#    port: 8089   # 톰캣 AJP 포트 설정
#    secretRequired: false
file:
  uploadDir: D:\gunyang\upload 
spring:
  mailType: SpringFramework
#  mailType: JavaMail
  fileAttached: YES 
#  mail:
#    default-encoding: UTF-8
#    host: smtp.office365.com
#    port: 587
#    username: js.nam@gunyangitt.co.kr
#    password: 오피스365암호
#    properties:
#      mail:
#        debuger: true
#        smtp:
#          port: 587
#          transport:
#            protocol: smtps
#          auth: true
#          timeout: 15000
#          connectiontimeout: 15000
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            enable: false
#          socketFactory:
#            fallback: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: jangsub.nam
    password: 앱비밀번호등록
    properties:
      mail:
        debuger: true
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

          